// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

package frc.robot.subsystems.Climber;

import edu.wpi.first.math.MathUtil;
import edu.wpi.first.math.filter.SlewRateLimiter;
import com.revrobotics.spark.SparkBase.PersistMode;
import com.revrobotics.spark.SparkBase.ResetMode;
import com.revrobotics.spark.config.ClosedLoopConfig.FeedbackSensor;
import com.revrobotics.spark.config.SparkBaseConfig.IdleMode;
import com.revrobotics.spark.config.SparkFlexConfig;
import com.revrobotics.spark.config.SparkMaxConfig;

import edu.wpi.first.math.filter.SlewRateLimiter;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.wpilibj.RobotBase;
import edu.wpi.first.wpilibj.smartdashboard.Mechanism2d;
import edu.wpi.first.wpilibj.smartdashboard.MechanismLigament2d;
import edu.wpi.first.wpilibj.smartdashboard.MechanismRoot2d;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.InstantCommand;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import edu.wpi.first.wpilibj2.command.button.Trigger;

import org.littletonrobotics.junction.Logger;

public class Climber extends SubsystemBase {
  private final ClimberIO io;
  private final ClimberIOInputsAutoLogged inputs = new ClimberIOInputsAutoLogged();

  private SlewRateLimiter rateLimit = new SlewRateLimiter(30);
  /** Climber setpoint for logging and checking */
  private double setpoint=100;

  /** Creates a new Climber. */
  public Climber() {
    SmartDashboard.putBoolean("simulate", false);
    if (RobotBase.isReal()) {
      this.io = new ClimberIOReal();
      // }else if(SmartDashboard.getBoolean("simulate", false)){
      // this.io = new ClimberIOSim();
    } else {
      this.io = new ClimberIO() {}; // Create a blank stub for replay
    }

    rateLimit.reset(io.getPosition());
    SmartDashboard.putData("mechanism/climber", mech);


    var config = new SparkMaxConfig();
    config.encoder.positionConversionFactor((360 / (9424 / 203.0)));
    config.absoluteEncoder.positionConversionFactor(360);
    config.absoluteEncoder.inverted(true);
    config
        .closedLoop
        .outputRange(-0.1, 0.1)
        .p(0.1 / 90.0)
        .feedbackSensor(FeedbackSensor.kAbsoluteEncoder)
        .positionWrappingEnabled(true);
    config
        .idleMode(IdleMode.kCoast)
        .smartCurrentLimit(0)
        .voltageCompensation(11.0)
        ;
    io.configure(config, ResetMode.kResetSafeParameters, PersistMode.kNoPersistParameters);


    // setDefaultCommand(setAngle(0));

    isOnTarget = new Trigger(()->MathUtil.isNear(setpoint, io.getPosition(), 3));
  }

  @Override
  public void periodic() {
    // Update our simulation mechanism for viewing experience
    updateMechanism();

    //update and log inputs
    //TODO: We do not know the inputs to update yet, because 
    //they're generated by motor controller: Which is an IO/Real/Sim distinction.
    //We need to read them from the sim, and *then* have it log them.
    //Which makes this wrong
    io.updateInputs(inputs);
    Logger.processInputs("Climber", inputs);
  }


  public Command prepareToClimb() {
    return setAngle(0);
  }

  public Command climb() {
    return new InstantCommand(()->setIdleMode(IdleMode.kBrake))
    .andThen(setAngle(90));
  }
  
  public Command setAngle(double angle) {
    return run(() -> setPosition(angle));
  }

  public Trigger isOnTarget;// Must be initialized in constructor after IO


  private void setPosition(double angle) {
    io.setReference(angle);
  }

  public void setIdleMode(IdleMode idleMode) {
    var config = new SparkFlexConfig().idleMode(idleMode);
    io.configureAsync(config, ResetMode.kNoResetSafeParameters, PersistMode.kNoPersistParameters);
  }

  // public void applyConfig(SparkFlexConfig config,ResetMode resetMode,PersistMode persistMode){
  //   io.applyConfig(config, resetMode, persistMode);
  // }

  // Create the basic mechanism construction
  Mechanism2d mech = new Mechanism2d(20, 20);
  MechanismRoot2d root = mech.getRoot("ClimberRoot", 10, 10);
  MechanismLigament2d pivot = root.append(new MechanismLigament2d("ClimberPivot", 4, 0));
  MechanismLigament2d top = pivot.append(new MechanismLigament2d("ClimberPivotTop", 4, 90));
  MechanismLigament2d bot = pivot.append(new MechanismLigament2d("ClimberPivotBottom", 4, -90));

  private void updateMechanism() {
    pivot.setAngle(new Rotation2d(Math.toRadians(io.getPosition())));
  }
}
